- name: Fetch data from SportsDataIO
  run: |
    mkdir -p public/data
    node <<'EOF'
    const fetch = require('node-fetch');
    const fs = require('fs');

    // Replace with your actual week/year or keep as variables
    const year = 2025;
    const week = 1;
    const API_KEY = process.env.SPORTSDATAIO_API_KEY;
    const url = `https://api.sportsdata.io/v3/nfl/stats/json/PlayerGameStatsByWeekFinal/${year}/${week}?key=${API_KEY}`;

    fetch(url)
      .then(res => res.json())
      .then(data => {
        console.log("Players fetched:", data.length);
        fs.writeFileSync("public/data/players.json", JSON.stringify({ players: data }, null, 2));
      })
      .catch(err => {
        console.error("❌ Error fetching data:", err);
        process.exit(1);
      });
    EOF
  env:
    SPORTSDATAIO_API_KEY: ${{ secrets.SPORTSDATAIO_API_KEY }}
